# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from data_fetcher import fetch_market_data

# Per-ticker model cache: {ticker_symbol: trained_model}
_ml_models = {}

def calculate_ml_features(df: pd.DataFrame) -> pd.DataFrame:
    """Engineer ADVANCED features for the ML model based on OHLCV data."""
    df = df.copy()
    
    # 1. Technical Indicators
    df['EMA_9'] = df['Close'].ewm(span=9, adjust=False).mean()
    df['EMA_21'] = df['Close'].ewm(span=21, adjust=False).mean()
    
    # RSI (14 period)
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / (loss + 1e-9)
    df['RSI'] = 100 - (100 / (1 + rs))
    
    # MACD
    ema_12 = df['Close'].ewm(span=12, adjust=False).mean()
    ema_26 = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = ema_12 - ema_26
    df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_Hist'] = df['MACD'] - df['MACD_Signal']
    
    # ADVANCED: Bollinger Bands
    df['BB_Mid'] = df['Close'].rolling(window=20).mean()
    df['BB_Std'] = df['Close'].rolling(window=20).std()
    df['BB_Upper'] = df['BB_Mid'] + (df['BB_Std'] * 2)
    df['BB_Lower'] = df['BB_Mid'] - (df['BB_Std'] * 2)
    df['BB_Width'] = (df['BB_Upper'] - df['BB_Lower']) / df['BB_Mid'] * 100
    df['BB_Percent'] = (df['Close'] - df['BB_Lower']) / (df['BB_Upper'] - df['BB_Lower'] + 1e-9)
    
    # ADVANCED: Stochastic Oscillator
    low_14 = df['Low'].rolling(window=14).min()
    high_14 = df['High'].rolling(window=14).max()
    df['Stoch_K'] = 100 * ((df['Close'] - low_14) / (high_14 - low_14 + 1e-9))
    df['Stoch_D'] = df['Stoch_K'].rolling(window=3).mean()
    
    # ADVANCED: Rate of Change (ROC)
    df['ROC_9'] = df['Close'].pct_change(9) * 100
    
    # ADVANCED: Lagged Features (Memory of previous candle)
    df['RSI_Lag1'] = df['RSI'].shift(1)
    df['MACD_Hist_Lag1'] = df['MACD_Hist'].shift(1)
    
    # 2. Distance from Moving Averages (Normalized)
    df['Dist_EMA9'] = (df['Close'] - df['EMA_9']) / df['Close'] * 100
    df['Dist_EMA21'] = (df['Close'] - df['EMA_21']) / df['Close'] * 100
    
    # 4. Volatility
    df['High_Low_Range'] = (df['High'] - df['Low']) / df['Close'] * 100
    
    # Drop rows with NaN values generated by rolling windows
    df = df.dropna()
    return df

# ADVANCED FEATURE SET
ADVANCED_FEATURES = [
    'RSI', 'MACD_Hist', 'Dist_EMA9', 'Dist_EMA21', 'High_Low_Range',
    'BB_Width', 'BB_Percent', 'Stoch_K', 'Stoch_D', 'ROC_9', 'RSI_Lag1', 'MACD_Hist_Lag1'
]

def train_ml_model(ticker="^NSEI"):
    """
    Fetches 60 days of 15m data, calculates features, and trains a Random Forest.
    Each ticker gets its own dedicated model cached in _ml_models.
    """
    global _ml_models
    
    print(f"[ML] Fetching data for {ticker}...")
    df = fetch_market_data(ticker, interval="15m", period="60d")
    
    if df.empty or len(df) < 100:
        print(f"[ML] Not enough data for {ticker}.")
        return False
        
    df = calculate_ml_features(df)
    
    # Target: price 4 candles (1 hour) ahead > 0.1% move
    future_returns = df['Close'].shift(-4) / df['Close'] - 1
    df['Target'] = np.where(future_returns > 0.001, 1, 0)
    df = df.dropna()
    
    X = df[ADVANCED_FEATURES]
    y = df['Target']
    
    print(f"[ML] Training ADVANCED Random Forest for {ticker} on {len(X)} samples...")
    model = RandomForestClassifier(n_estimators=200, max_depth=7, min_samples_leaf=3, random_state=42)
    model.fit(X, y)
    
    _ml_models[ticker] = model
    print(f"[ML] Training complete for {ticker}.")
    return True

def _get_strike_step(ticker: str) -> int:
    """Returns the ATM strike rounding step for a given ticker."""
    if ticker in ("^NSEI", "NIFTY_FIN_SERVICE.NS"):
        return 50
    elif ticker == "^NSEBANK":
        return 100
    else:
        # For individual stocks — round to nearest 5 or 10
        return 10

def predict_breakout_probability(df_recent: pd.DataFrame, ticker: str = "^NSEI") -> dict:
    """
    Uses the per-ticker trained ML model to predict the probability of a bullish breakout.
    If that ticker's model is not yet trained, trains it on-demand.
    """
    global _ml_models
    
    if ticker not in _ml_models:
        success = train_ml_model(ticker)
        if not success:
            return {"probability": 50, "prediction": "Model Error", "status": "Untrained"}
            
    try:
        df_feat = calculate_ml_features(df_recent)
        
        if df_feat.empty:
            return {"probability": 50, "prediction": "Not enough data", "status": "Ready"}
            
        latest_features = df_feat[ADVANCED_FEATURES].iloc[-1:]
        prob_bullish = _ml_models[ticker].predict_proba(latest_features)[0][1] * 100
        
        prediction = "Bullish" if prob_bullish >= 50 else "Bearish"
        confidence = round(prob_bullish if prediction == "Bullish" else 100 - prob_bullish, 1)
        
        # Calculate ATM Strike using ticker-appropriate step
        current_price = df_feat['Close'].iloc[-1]
        step = _get_strike_step(ticker)
        atm_strike = int(round(current_price / step) * step)
        
        ml_strike = f"{atm_strike} CE" if prediction == "Bullish" else f"{atm_strike} PE"

        return {
            "probability": confidence,
            "prediction": prediction,
            "strike": ml_strike,
            "status": "Live"
        }
    except Exception as e:
        print(f"[ML] Prediction error for {ticker}: {e}")
        return {"probability": 50, "prediction": "Error", "status": "Error"}

def predict_historical_batch(df: pd.DataFrame, ticker: str = "^NSEI") -> pd.DataFrame:
    """
    Vectorized prediction for historical backtesting.
    Uses the per-ticker model cache.
    """
    global _ml_models
    
    if ticker not in _ml_models:
        train_ml_model(ticker)
        if ticker not in _ml_models:
            df['ML_Prediction'] = "Wait"
            df['ML_Confidence'] = 50.0
            return df
            
    df_feat = calculate_ml_features(df)
    df_pred = df_feat.dropna(subset=ADVANCED_FEATURES).copy()
    
    if df_pred.empty:
        df['ML_Prediction'] = "Wait"
        df['ML_Confidence'] = 50.0
        return df
        
    X = df_pred[ADVANCED_FEATURES]
    
    probs = _ml_models[ticker].predict_proba(X)
    df_pred['ML_Bullish_Prob'] = probs[:, 1] * 100
    df_pred['ML_Prediction'] = np.where(df_pred['ML_Bullish_Prob'] >= 50, 'Bullish', 'Bearish')
    df_pred['ML_Confidence'] = np.where(df_pred['ML_Prediction'] == 'Bullish', df_pred['ML_Bullish_Prob'],
                                 100 - df_pred['ML_Bullish_Prob'])
                                 
    result = df.copy()
    result = result.join(df_pred[['ML_Bullish_Prob', 'ML_Prediction', 'ML_Confidence']], how='left')
    result['ML_Prediction'] = result['ML_Prediction'].fillna("Wait")
    result['ML_Confidence'] = result['ML_Confidence'].fillna(50.0)
    result['ML_Bullish_Prob'] = result['ML_Bullish_Prob'].fillna(50.0)
    
    return result

if __name__ == '__main__':
    print('[ML] Starting Advanced ML Model Training Pipeline...')
    train_ml_model()
    print('[ML] Training complete.')
